### ISSUE TITLE
PlaceholderAPI takes a second to load on first join and doesnt format if it has characters in front.

### ISSUE THREAD

**Issue by tomkeuper** [andrei1058/SidebarLib#21]
When you join a server with a scoreboard the papi placeholders take a second to load in and will first show the full string.
The placeholder shown in the video is %vault_eco_balance_formatted% but it will happen with any placeholder.

https://youtu.be/w848qyXOFJc 

Text in front stops the placeholders from loading completly. 
![image](https://user-images.githubusercontent.com/29728836/227054639-68ffb9c2-fa71-4c24-a265-ead772ac2e4a.png)
After going into an arena and leaving again it does work:
![image](https://user-images.githubusercontent.com/29728836/227054797-1d254be8-cb22-4bf1-bf97-ca69d35c45a1.png)

Bedwars version: 23.2.2-BETA3 (up untill commit [52f4e63ed196cac0b940b6f9cd4c4d81466ffe27](https://github.com/andrei1058/BedWars1058/tree/52f4e63ed196cac0b940b6f9cd4c4d81466ffe27) )
Server version 1.8.8

**Comment by tomkeuper** [comment]
![image](https://user-images.githubusercontent.com/29728836/227056961-ee7e3deb-730e-440d-9036-ddccb592237d.png)
It has something to do with the space in front

This does work:
![image](https://user-images.githubusercontent.com/29728836/227057124-b4dfcf6e-8f37-4339-92a5-22cb067a78a2.png)

But if you remove the space in front of the placeholder it doesnt

**Comment by andrei1058** [comment]
I can't reproduce this on 1.19.3
