### ISSUE TITLE
Add 1.20.2 Support

### ISSUE THREAD

**Issue by ImYenil** [andrei1058/SidebarLib#32]
Can you add support for version 1.20.2? Some code has changed

**Comment by andrei1058** [comment]
really? will look into that next week

**Comment by ImYenil** [comment]
> really? will look into that next week

Yes

**Comment by andrei1058** [comment]
@ImYenil are you using this lib in any of your resources?

**Comment by ImYenil** [comment]
> @ImYenil are you using this lib in any of your resources?

No. Yesterday bedwars1058 made a pull request to support 1.20.2, but this library does not support version 1.20.2 yet.
